#  origem
#   https://hub.docker.com/_/php
#   https://hub.docker.com/_/redis
#   https://github.com/ineat/docker-php-nginx-postgres-composer
#   https://www.elastic.co/guide/en/elasticsearch/reference/6.7/docker.html
#   https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
#
version: '3'
services:
    dojo-postgres:
        build: .docker/conf/postgres
        restart: always
        environment:
            - POSTGRES_DB=dojo
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=qaz123
        ports:
            - 5454:5432
        volumes:
            - ../:/dojo
            - .docker/data/database:/var/lib/postgresql
        depends_on:
            - dojo-redis

    dojo-parser:
        build: .docker/conf/php
        restart: always
        volumes:
            - ../:/dojo

    dojo-redis:
        image: redis:4.0.14-alpine
        restart: always
        environment:
            - discovery.type=single-node
        ports:
            - 6379:6379
        volumes:
            - ../:/dojo
            - .docker/data/redis:/data

    dojo-es:
        image: elasticsearch:7.0.1
        restart: always
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        volumes:
            - ../:/dojo
            - .docker/data/es:/usr/share/elasticsearch/data
